apiVersion: v1
kind: ConfigMap
metadata:
  name: stapp-appconfig
  labels:
    {{- include "stapp.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ toYaml .Values.appConfig | nindent 4 | trim }}