apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-appconfig
  labels:
    {{- include "lp-number-detection-backend.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ toYaml .Values.backend.appConfig | nindent 4 | trim }}