FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 vim \
    && rm -rf /var/lib/apt/lists/*

COPY ./frontend-requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt
