FROM python:3.11-slim

WORKDIR /app

# opencv-python dependencies
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 vim \
    build-essential cmake git python3-dev python3-numpy \
    libavcodec-dev libavformat-dev libswscale-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer1.0-dev libgtk-3-dev \
    libpng-dev libjpeg-dev libopenexr-dev libtiff-dev libwebp-dev \
    libopencv-dev x264 libx264-dev libssl-dev ffmpeg \
    && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --no-binary opencv-python opencv-python


