{{- if .Values.inferenceService.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lp-number-detection-isvc.serviceAccountName" . }}
secrets:
  - name: {{ include "lp-number-detection-isvc.fullname" . }}
{{- end }}