{{- if .Values.inferenceService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lp-number-detection-isvc.fullname" . }}
  annotations:
    serving.kserve.io/s3-cabundle: ""
    serving.kserve.io/s3-endpoint: "local-s3-service.ezdata-system.svc.cluster.local:30000/"
    serving.kserve.io/s3-useanoncredential: "false"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-verifyssl: "0"
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.inferenceService.storageCredential }}
  AWS_SECRET_ACCESS_KEY: "s3"
type: Opaque
{{- end }}